# Generated by Django 2.2.4 on 2019-12-05 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokedexs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pokemon',
            options={},
        ),
    ]
